### PR TITLE
Attempt to write cleaner README

### PR DESCRIPTION
**Pull request by hankache**

### CODE REVIEW

**Comment by hankache** [comment]
@Leont Can you kindly review these changes.

They are mostly documentation.

**Comment by hankache** [comment]
@Leont kind reminder.

**Comment by Leont** [comment]
I could rebase these for me? In particular I'd like to see the first commit split in two (one for fixing the POD in prove6, and one for adding that README); and make it clear in the commit message that it's a README for prove6 specifically? And could you squash the typo fix into the other commit?

I have no idea if having pods in `bin/` is allowed (I wouldn't want them to be installed as if they're scripts), have you verified this? (I realize this may is a stupid question; I'm not well aware about norms in other Perl6 projects).

**Comment by hankache** [comment]
I botched this PR. I will close it and open a new one.

**Comment by hankache** [comment]
@Leont The changes you asked for should be catered for by #24  
Thanks.

**Pull request closed without merging**
